# Generated by Django 4.0.4 on 2022-05-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='instructions',
            field=models.TextField(default='', max_length=95),
            preserve_default=False,
        ),
    ]
