# Generated by Django 4.0.4 on 2022-05-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_order_description_order_done_alter_foodorder_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
